// <auto-generated />
using System;
using ExpenseApprovalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseApprovalSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseApprovalSystem.Models.ApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.ApprovalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxAmount = 5000m,
                            MinAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            MaxAmount = 20000m,
                            MinAmount = 5001m
                        },
                        new
                        {
                            Id = 3,
                            MinAmount = 20001m
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.ApprovalRuleLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("ApprovalRuleLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApproverType = "Manager",
                            RuleId = 1,
                            Sequence = 1
                        },
                        new
                        {
                            Id = 2,
                            ApproverType = "Manager",
                            RuleId = 2,
                            Sequence = 1
                        },
                        new
                        {
                            Id = 3,
                            ApproverType = "DepartmentHead",
                            RuleId = 2,
                            Sequence = 2
                        },
                        new
                        {
                            Id = 4,
                            ApproverType = "Manager",
                            RuleId = 3,
                            Sequence = 1
                        },
                        new
                        {
                            Id = 5,
                            ApproverType = "DepartmentHead",
                            RuleId = 3,
                            Sequence = 2
                        },
                        new
                        {
                            Id = 6,
                            ApproverType = "CFO",
                            RuleId = 3,
                            Sequence = 3
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HeadId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmitterId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DepartmentHead"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CFO"
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john@company.com",
                            ManagerId = 4,
                            Name = "John Doe",
                            PasswordHash = "password123",
                            RoleId = 1,
                            Username = "john"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "jane@company.com",
                            ManagerId = 4,
                            Name = "Jane Smith",
                            PasswordHash = "password123",
                            RoleId = 1,
                            Username = "jane"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "bob@company.com",
                            ManagerId = 6,
                            Name = "Bob Wilson",
                            PasswordHash = "password123",
                            RoleId = 1,
                            Username = "bob"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "alice@company.com",
                            ManagerId = 7,
                            Name = "Alice Brown",
                            PasswordHash = "password123",
                            RoleId = 2,
                            Username = "alice"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "mike@company.com",
                            ManagerId = 5,
                            Name = "Mike Lee",
                            PasswordHash = "password123",
                            RoleId = 2,
                            Username = "mike"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Email = "david@company.com",
                            Name = "David Kim",
                            PasswordHash = "password123",
                            RoleId = 3,
                            Username = "david"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Email = "sarah@company.com",
                            Name = "Sarah Connor",
                            PasswordHash = "password123",
                            RoleId = 3,
                            Username = "sarah"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Email = "cfo@company.com",
                            Name = "CFO",
                            PasswordHash = "password123",
                            RoleId = 4,
                            Username = "cfo"
                        });
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.ApprovalHistory", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseApprovalSystem.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.ApprovalRuleLevel", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Models.ApprovalRule", "Rule")
                        .WithMany("Levels")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.Department", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Models.User", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Head");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.Expense", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Models.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.User", b =>
                {
                    b.HasOne("ExpenseApprovalSystem.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseApprovalSystem.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ExpenseApprovalSystem.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExpenseApprovalSystem.Models.ApprovalRule", b =>
                {
                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
